name: reddit_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  collection: ^1.16.0
  dio: ^4.0.6
  dynamic_color: ^1.5.4
  equatable: ^2.0.5
  flex_color_scheme: ^6.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.13
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.2
  page_transition: ^2.0.9
  path: ^1.8.2
  path_provider: ^2.0.11
  video_player: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
