name: reddit_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  collection: ^1.16.0
  dio: ^5.0.1
  dismissible_page: ^1.0.1
  dynamic_color: ^1.6.2
  equatable: ^2.0.5
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_easyloading: ^3.0.5
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  html: ^0.15.2
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  inview_notifier_list: ^3.0.0
  material_design_icons_flutter: ^6.0.7096
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  page_transition: ^2.0.9
  palette_generator: ^0.3.3+2
  path: ^1.8.2
  path_provider: ^2.0.12
  rxdart: ^0.27.7
  url_launcher: ^6.1.10
  video_player: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
